### ISSUE TITLE
Inject spring beans in changelogs

### ISSUE THREAD

**Issue by santam85** [cloudyrock/mongock-examples#1]
I am building a changelog that needs some external information to remap data.
I'd like to inject a Bean from the application context to retrieve this informaton, but if I follow the instructions at https://www.mongock.io/injecting-custom-dependencies-to-changesets the application fails to start:
`Error in method [...] Wrong parameter[BeanClass]`
What am I doing wrong? Is it because my bean is not a Repository?

**Comment by dieppa** [comment]
I need a bit more information.
Let me see your changeLog(I don't need the logic inside, just how you are defining the changeSets) and the log stack trace.

cheers

**Comment by santam85** [comment]
The signature of the changeset is:
```
@ChangeSet(author = "marco", id = "stackcountries", order = "001", systemVersion = "1.6.0")
public void convertCountryToISOCode(MongockTemplate mongockTemplate, RestTemplate restTemplate) {
```

Which is causing: 
```
com.github.cloudyrock.mongock.exception.MongockException: Error in method[StackCountriesChangeLog.convertCountryToISOCode] : Wrong parameter[RestTemplate]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processExceptionOnChangeSetExecution(MigrationExecutor.java:194)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:101)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processSingleChangeLog$2(MigrationExecutor.java:93)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:79)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeLog(MigrationExecutor.java:93)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$processAllChangeLogs$1(MigrationExecutor.java:87)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:79)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processAllChangeLogs(MigrationExecutor.java:87)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$executeMigration$0(MigrationExecutor.java:68)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeInTransactionIfStrategyOrUsualIfNot(MigrationExecutor.java:79)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeMigration(MigrationExecutor.java:68)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeMigration(SpringMigrationExecutor.java:37)
	at com.github.cloudyrock.mongock.runner.core.executor.MongockRunnerBase.execute(MongockRunnerBase.java:53)
	at com.github.cloudyrock.spring.v5.MongockSpring5$MongockApplicationRunner.run(MongockSpring5.java:68)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)

Caused by: com.github.cloudyrock.mongock.driver.api.common.DependencyInjectionException: Wrong parameter[RestTemplate]
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.lambda$getParameter$4(MigrationExecutor.java:181)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.getParameter(MigrationExecutor.java:181)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeChangeSetMethod(MigrationExecutor.java:170)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.executeAndLogChangeSet(MigrationExecutor.java:126)
	at com.github.cloudyrock.spring.v5.core.SpringMigrationExecutor.executeAndLogChangeSet(SpringMigrationExecutor.java:43)
	at com.github.cloudyrock.mongock.runner.core.executor.MigrationExecutor.processSingleChangeSet(MigrationExecutor.java:99)
	... 18 common frames omitted```

**Comment by dieppa** [comment]
Although I would appreciate you to show me the signature of the restTemplate, I think I am right if I say that it's not a interface.

So, you have two solutions here:
- If your RestTemplate writes to MongoDB and you want those writes to be synchronised and lock-guaranteed, you need to create an interface for it and inject it as a bean.

- If you don't need to cover it by the Mongock lock, you can add the annotation @NonLockGuarded. You can add this annotation in the changeSet parameter, in your RestTemplate class(I guess this is the spring RestTemplate, so you probably won't be able) or in your bean method. 

[This section](https://www.mongock.io/injecting-custom-dependencies-to-changesets#advance-configuration-prevent-proxing-my-beans) of the Mongock documentation explains it.

Please let me know how it goes ;)

**Comment by dieppa** [comment]
Although it's a totally fine channel, I would appreciate you to add this question to stackoverflow, so other users can benefit from it easier :)
